### ISSUE TITLE
Exception decoder does not decode exception cause

### ISSUE THREAD

**Issue by burner-** [me-no-dev/EspExceptionDecoder#11]
This is more like feature request than bug issue. Currently exception decoder decode only call stack but not Exception cause, reset cause etc information whan can be also very usefull. 

Example newest git master version of esp8266 arduino core  crash if it get too busy with http. 

Exception (2):
epc1=0x3ffea958 epc2=0x00000000 epc3=0x00000000 excvaddr=0x3ffea958 depc=0x00000000

ctx: sys 
sp: 3ffffd80 end: 3fffffb0 offset: 01a0

> > > stack>>>
> > > 3fffff20:  3fff23d0 3ffefb50 3ffeebf0 401077d8  
> > > 3fffff30:  4021f5f9 3ffeebf0 3ffefb50 06812c93  
> > > 3fffff40:  3fff567c 00001000 4021fad2 00000008  
> > > 3fffff50:  00000000 00000000 4021fb97 3ffeeca4  
> > > 3fffff60:  3ffefb50 020838d3 3ffefb50 40201fe0  
> > > 3fffff70:  40239941 3ffeeca4 3ffefb50 06811e4d  
> > > 3fffff80:  40239986 3fffdab0 00000000 3fffdcb0  
> > > 3fffff90:  3ffefb78 3fffdad0 3fff0eac 402133b3  
> > > 3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
> > > <<<stack<<<
> > > ets Jan  8 2013,rst cause:2, boot mode:(3,6)

Decoding 11 results
0x401077d8: pvPortZalloc at C:\Arduino\arduino-1.6.11\hardware\esp8266com\esp8266\cores\esp8266/heap.c line 54
0x4021f5f9: pm_set_sleep_time at ?? line ?
0x4021fad2: pm_get_sleep_type at ?? line ?
0x4021fb97: pm_get_sleep_type at ?? line ?
0x40201fe0: delay_end at C:\Arduino\arduino-1.6.11\hardware\esp8266com\esp8266\cores\esp8266/core_esp8266_wiring.c line 40
0x40239941: ets_timer_handler_isr at ?? line ?
0x40239986: ets_timer_handler_isr at ?? line ?
0x402133b3: loop_task at C:\Arduino\arduino-1.6.11\hardware\esp8266com\esp8266\cores\esp8266/core_esp8266_main.cpp line 56

But that does not tell much why it crash. Probably cause codes tell something about reason but they are not decoded?

**Comment by me-no-dev** [comment]
fixed in the latest release :)
