### ISSUE TITLE
gedit language file for highlighting

### ISSUE THREAD

**Issue by electronicsguy** [me-no-dev/EspExceptionDecoder#12]
Thanks for this tool me-no-dev. I made a gedit language file for highlighting the output from your tool, for easy viewing. Available here: [stacktrace.lang](https://github.com/electronicsguy/ESP8266/tree/master/Misc/Tools)

Let me know how you like it.

**Comment by me-no-dev** [comment]
Nice! Want to make PR to update README with link and usage?

**Comment by electronicsguy** [comment]
Thanks Hristo. done.

**Comment by me-no-dev** [comment]
Merged :) How you know my name? :D

**Comment by EagleSmith** [comment]
beause you are the esp-star

**Comment by me-no-dev** [comment]
didn't ask for compliment, but wow :) thanks!

**Comment by electronicsguy** [comment]
@me-no-dev   it's in the project source file

**Comment by me-no-dev** [comment]
Have recently started yes :) Working on the [Arduino for ESP32](https://github.com/espressif/arduino-esp32)
