### ISSUE TITLE
Error: Did you forget to compile the sketch?

### ISSUE THREAD

**Issue by raymusmunt** [me-no-dev/EspExceptionDecoder#14]
Sketch definitely compiled.  This is the error I get when trying to use the Decoder:
Did you forget to compile the sketch?

Mac OSX 10.11.6
Arduino IDE 1.6.12
ESP8266 2.3.0

**Comment by RudyFiero** [comment]
I get the same thing. I did a search and both files exist.
 
I am running Windows 10
Arduino 1.6.12
ESP8266 2.3.0

**Comment by me-no-dev** [comment]
FIXED! if elf is not found a dialog will be shown to manually locate it
please download latest release

**Comment by RudyFiero** [comment]
Thank you. :)
