### ISSUE TITLE
when i open decoder it is asking for elf files 

### ISSUE THREAD

**Issue by rahulbommaraju** [me-no-dev/EspExceptionDecoder#25]
when i open esp exception decoder it is assking for .elf files to select, i can't understand what it is!!

**Comment by me-no-dev** [comment]
Compile the sketch and it will not ask for elf

**Comment by rahulbommaraju** [comment]
ohh ok thank you

**Comment by prampec** [comment]
Should be part of the README

**Comment by cybermonk00** [comment]
> Compile the sketch and it will not ask for elf

Thanks for answer.

**Comment by Mr-m-shahbazi** [comment]
> Compile the sketch and it will not ask for elf

Thanks for answer
