### ISSUE TITLE
[Feature request] Add Exception code info

### ISSUE THREAD

**Issue by av1024** [me-no-dev/EspExceptionDecoder#3]
It will be cool if 'Exception(XX)' text would be decoded using for example [this](https://github.com/esp8266/Arduino/blob/master/doc/exception_causes.md) table (at least cause name and description)

**Comment by me-no-dev** [comment]
should be visible in the trace itself? is it not? that is the reason I did not put it there

**Comment by av1024** [comment]
There is only "Exception (28)" (for example) in trace. Sometimes with short exception name.

I am not very familiar with Java so I made monkey-patched version for my cubietruck's arduino 1.6.5 with java 1.7 (git code does not compiles with error near FileUtils usage): https://gist.github.com/av1024/018ffd57fae7e7f9d353

This is almost exactly what I want. As an perfect solution I want any suggestion like "Hey! Check PSTR/F/etc usage" for this exception ;)

**Comment by me-no-dev** [comment]
I don't know how I forgot about this...
I looked through your code and it looks good but I know that there are gaps in the exception cause table or at least there are on the ESP32. Also maybe we should check if they are the same and use a two dimensional array to map the exception number with the exception string.
Where did you get your exception table from?

**Comment by me-no-dev** [comment]
seems I read it with my ass... nevermind :) will merge it to the current source

**Comment by av1024** [comment]
:))
BTW, is the ESP32 codes same as ESP8266? May be you should check what chip used?...

**Comment by me-no-dev** [comment]
it's not exactly the same because the hardware is a bit different and it's running RTOS but it's on the same architecture :) you can check my ESP31B repo which is the arduino env for the new chip.
We have lots of headers there :)

**Comment by av1024** [comment]
Looks promising!
But... I have 8 of 10 [PCB's](https://bitbucket.org/repo/9GdA6p/images/3496538974-board.jpg) for ESP8266 unsoldered so ESP31B not for me at least for half of year ))

Hmm.. Thinking out loud. When I wrote this patch I wanted to write a parser for wiki page... May be an "external" (local file or web link?) message source will be a solution? This will be helpful for updating and (for example) translation.

**Comment by me-no-dev** [comment]
that is actually not a bad idea! I will see what options do I have to access local files for the tool. Maybe there is an option for translation...

**Comment by me-no-dev** [comment]
BTW it looks like the exception numbers are the same for both chips, so we can go with single table for now.

**Comment by me-no-dev** [comment]
fixed in the latest release :)
