### ISSUE TITLE
Arch Not Found for ESP32 Wrover Module

### ISSUE THREAD

**Issue by gorghino** [me-no-dev/EspExceptionDecoder#78]
ESPExceptionDecoder v. 2.0.2

Arch Not Found for 'ESP32 Wrover Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), QIO, 80MHz, 115200, Verbose'. Defaulting to 'xtensa'
Target Not Found for 'ESP32 Wrover Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), QIO, 80MHz, 115200, Verbose'. Defaulting to 'esp32'

I'm using a Lilygo TTGO SIM7600E-H with ESP32-WROVER-B

**Comment by me-no-dev** [comment]
this is not an error. It just shows you are using an old ESP32 core and it defaulted to that.
